version: '3.9'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ems_manage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewPassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ems_network

blue_app:
  build: .
  container_name: ems_blue_app
ports:
    - "5001:5000"
environment:
    DB_HOST: db
    FLASK_ENV: production
depends_on:
    db:
      condtion: service_healthy
    networks:
      - ems_network

green_app:
  build: .
  container_namme: ems_green_app
  ports:
    - "5002:5000"
  environment:
    DB_hOST: db
    FLASK_ENV: production
  depends_on:
    db:
      condition: service_healthy
    networks:
      - ems_network

volumes:
  postgres_data:

networks:
  ems_network:
    driver: bridge