name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d ~/employee-management-system ]; then
              git clone https://github.com/shilasonavane206-dot/employee-management-system.git ~/employee-management-system
            fi

            cd ~/employee-management-system

            git pull origin main

            docker compose down || true

            docker compose up -d --build

            docker ps